server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:carBrand
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true

isa:
  carBrand:
    url: http://localhost:8081/
    url.delete: /carBrands/{id}
    url.put: /carBrands/{id}
    url.post: /carBrands